import os
import typer
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from utils import plan_sub_questions, research_sub_question, synthesize_report

load_dotenv()
app = typer.Typer()
console = Console()


@app.command()
def run(
    question: str = typer.Argument(..., help="The research question to investigate"),
    output_dir: str = typer.Option("outputs", help="Directory to save the report"),
    depth: int = typer.Option(3, help="Research depth 1-10: controls number of sub-questions researched."),
):
    """AutoResearch Agent — give it a question, get back a full cited report."""

    if not 1 <= depth <= 10:
        console.print("[bold red]Error:[/bold red] --depth must be between 1 and 10.")
        raise typer.Exit(1)

    if not os.getenv("ANTHROPIC_API_KEY"):
        console.print("[bold red]Error:[/bold red] ANTHROPIC_API_KEY not set. Copy .env.example to .env and add your key.")
        raise typer.Exit(1)

    console.print(Panel(f"[bold white]{question}[/bold white]", title="🤖 AutoResearch Agent", border_style="blue"))

    # Step 1: Plan
    sub_questions = plan_sub_questions(question, depth=depth)

    # Step 2: Research each sub-question
    research_data = {}
    for sub_q in sub_questions:
        research_data[sub_q] = research_sub_question(sub_q)

    # Step 3: Synthesize
    report = synthesize_report(question, research_data)

    # Step 4: Save
    Path(output_dir).mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = question[:40].lower().replace(" ", "_").replace("?", "")
    filename = f"{output_dir}/{timestamp}_{slug}.md"

    with open(filename, "w") as f:
        f.write(f"# {question}\n\n")
        f.write(f"*Generated by AutoResearch Agent on {datetime.now().strftime('%B %d, %Y')}*\n\n")
        f.write("---\n\n")
        f.write(report)

    console.print(f"\n[bold green]✅ Report saved to:[/bold green] {filename}")
    console.print("\n[dim]Preview (first 500 chars):[/dim]")
    console.print(report[:500] + "...")


if __name__ == "__main__":
    app()
