from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER


def _build_styles():
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=20,
            textColor=colors.HexColor("#1a1a2e"),
            spaceAfter=6,
            alignment=TA_CENTER,
        ),
        "meta": ParagraphStyle(
            "Meta",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=16,
            alignment=TA_CENTER,
        ),
        "h2": ParagraphStyle(
            "H2",
            parent=base["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#16213e"),
            spaceBefore=14,
            spaceAfter=4,
        ),
        "h3": ParagraphStyle(
            "H3",
            parent=base["Heading3"],
            fontSize=11,
            textColor=colors.HexColor("#0f3460"),
            spaceBefore=10,
            spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=15,
            spaceAfter=6,
        ),
        "bullet": ParagraphStyle(
            "Bullet",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
            leftIndent=18,
            bulletIndent=6,
            spaceAfter=3,
        ),
    }
    return styles


def markdown_to_pdf(question: str, report_text: str, output_path: str) -> str:
    """Convert a markdown report string to a styled PDF file."""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = _build_styles()
    story = []

    # Title block
    story.append(Paragraph(question, styles["title"]))
    story.append(Paragraph(
        f"Generated by AutoResearch Agent &bull; {datetime.now().strftime('%B %d, %Y')}",
        styles["meta"]
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 12))

    # Parse markdown lines
    for line in report_text.splitlines():
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 4))

        elif stripped.startswith("## "):
            text = stripped[3:].strip()
            story.append(Spacer(1, 6))
            story.append(Paragraph(text, styles["h2"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#eeeeee")))

        elif stripped.startswith("### "):
            text = stripped[4:].strip()
            story.append(Paragraph(text, styles["h3"]))

        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:].strip()
            text = _inline_format(text)
            story.append(Paragraph(f"&bull; {text}", styles["bullet"]))

        elif stripped.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
            story.append(Spacer(1, 4))

        else:
            text = _inline_format(stripped)
            story.append(Paragraph(text, styles["body"]))

    doc.build(story)
    return output_path


def _inline_format(text: str) -> str:
    """Convert markdown formatting and URLs to ReportLab XML tags."""
    import re
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Render URLs as blue underlined clickable links
    text = re.sub(
        r'(https?://[^\s<>"\)]+)',
        r'<link href="\1"><font color="#0ea5e9"><u>\1</u></font></link>',
        text
    )
    # Escape & that aren't already entities (but not inside href attributes)
    text = re.sub(r'&(?!(?:amp|lt|gt|bull|nbsp);)(?![^<]*>)', '&amp;', text)
    return text
